// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtI-1MXnxOlfMz4TDmUzW2VPlxYVC4rHQ',
    appId: '1:772804533220:web:02cc3705dd713a2dfdc5f1',
    messagingSenderId: '772804533220',
    projectId: 'shorts-f9314',
    authDomain: 'shorts-f9314.firebaseapp.com',
    storageBucket: 'shorts-f9314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN2njF_tYMGRz6_cgp2qQjNvqUcQ01fKI',
    appId: '1:772804533220:android:b982b63d4d862402fdc5f1',
    messagingSenderId: '772804533220',
    projectId: 'shorts-f9314',
    storageBucket: 'shorts-f9314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ktG55y8YGm5WKRPvQ6dV_ZcMXui3Dok',
    appId: '1:772804533220:ios:871e5f6e85381a42fdc5f1',
    messagingSenderId: '772804533220',
    projectId: 'shorts-f9314',
    storageBucket: 'shorts-f9314.appspot.com',
    iosBundleId: 'com.example.shorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ktG55y8YGm5WKRPvQ6dV_ZcMXui3Dok',
    appId: '1:772804533220:ios:871e5f6e85381a42fdc5f1',
    messagingSenderId: '772804533220',
    projectId: 'shorts-f9314',
    storageBucket: 'shorts-f9314.appspot.com',
    iosBundleId: 'com.example.shorts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtI-1MXnxOlfMz4TDmUzW2VPlxYVC4rHQ',
    appId: '1:772804533220:web:08199cfd868cc8cdfdc5f1',
    messagingSenderId: '772804533220',
    projectId: 'shorts-f9314',
    authDomain: 'shorts-f9314.firebaseapp.com',
    storageBucket: 'shorts-f9314.appspot.com',
  );
}
